version: "3.9"

services:
  telegram-upload:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      HOST: "0.0.0.0"
      PORT: "8805"
    ports:
      - "8805:8805"
    volumes:
      - app_uploads:/app/uploads
      - app_database:/app/database
    restart: always

volumes:
  app_uploads:
  app_database:


